### ISSUE TITLE
Return string from log methods (was "logwarn() and logdie()") [rt.cpan.org #83220]

### ISSUE THREAD

**Issue by dagolden** [preaction/Log-Any#18]
https://rt.cpan.org/Ticket/Display.html?id=83220

    Awesome module.  Love it and really hope it gets put in core perl.
    
    I was wondering if you'd consider adding logwarn() and logdie() methods?
     A number of logging packages (well at least log4Perl) contain these
    very useful shortcuts for logging with a warning or logging and then
    exiting.  Its rather nice to be able to replace:
    
    $logger->fatal($err) && die($err);
    
    with 
    
    $log->logdie($err);
    
    Cheers

**Comment by ebaudrez** [comment]
I agree wholeheartedly that Log::Any is a great module, and thank you to David for taking over.

Just for your information, this particular issue has been raised (on the RT queue), and the original author had this to say:

    Similar to other issue - though it would be convenient, default Log::Any
    behavior (no adapter selected - null adapter) needs to have no
    side-effects. It wouldn't be clear what the null adapter should do for
    error_die / fatal_die. This is something you'll have to write your own
    wrapper for I'm afraid... :(

(The other issue referred to was this:)

    How about the log methods returning the generated string? That would
    enable us to write, among others:
       die $log->fatalf("blah %s", $blah);

But I agree having logdie() would be nice if you can work out how to implement it.

**Comment by dagolden** [comment]
To the extent that "logdie" just encapsulates a log and a die call with the same error message, I think that's still "side effect free" for logging.

But returning the string so that you can `die $log->fatalf(...)` is sort of clever, too and doesn't require polluting the proxy with warn/die etc. variations.

**Comment by ebaudrez** [comment]
The cleverness is all Steven Haryanto's ;-)

Btw, the original issues were:
https://rt.cpan.org/Ticket/Display.html?id=56596
https://rt.cpan.org/Ticket/Display.html?id=56597

Regarding the latter, the original author commented that

    That would be convenient. However, it's important that the default case
    (no adapter chosen - the null adapter) be a no-op and have no
    performance cost, so that module authors are comfortable using logging
    statements liberally. In this case to be consistent the null adapter
    would still have to format the message and return it.

I'm not trying to be clever or pedantic. Just wanted to point this out, so this information won't get lost.

I've long wondered why the original author thought logwarn() or logdie() would have side-effects (other than the warning or dying, which should not be surprising to the caller). Is it because the null adapter would need to format the string for die(), and would hence stop being a null adapter?

**Comment by dagolden** [comment]
In a side email discussion -- not yet filed as an issue -- the idea of a "null" proxy came up to avoid overhead if the null adapter was selected.  If that becomes a thing, then having it return the string does become a problem.

**Comment by abraxxa** [comment]
Why not use ```wantarray``` to detect non-void context and only generate and return the string for that case?
