### ISSUE TITLE
Allow passing adapter parameters via get_logger(default_adapter => xxx)

### ISSUE THREAD

**Issue by bjakubski** [preaction/Log-Any#31]
It seems that Manager's set_default accepts ( $category, $adapter_name, @adapter_params), but when calling Log::Any->get_logger( default_adapter => $adapter_name ) there is no possibility to pass any @adapter_params.

It could be done either by allowing arrayref as default_adapter (in which case it would be interpreted as [$name, @params]. Or maybe by adding new parameter default_adapter_params
Hashref { name => $name, params => $params } is also possible but for some reason I don't like it. :-).

**Comment by xdg** [comment]
I'd be fine with allowing an arrayref `[$name, @params]` for `default_adapter`.  It's a good idea.  Do you want to send a PR (with tests)?

**Comment by bjakubski** [comment]
I forgot about docs. If that change looks ok then you can wait with merge and I'll add doc change later

**Comment by preaction** [comment]
It looks okay to me. What do I need to do before we can merge this? Just write some docs? Once that's done, I'll add this to the next release (1.042, since the 1.041 trial seems to be going well).

**Comment by bjakubski** [comment]
That would be great, thanks
