### ISSUE TITLE
Null proxy

### ISSUE THREAD

**Issue by xdg** [preaction/Log-Any#35]
It would be useful to have a "Null" proxy that NOPs its methods when there is no log consumer.

**Comment by xdg** [comment]
This could be complicated in combination with #18

**Comment by preaction** [comment]
#18 requires that the formatter, filter, and prefix all get executed even if there's no consumers. The only thing that wouldn't happen is the call to the adapter, which would save a hash lookup and a method call (probably not expensive enough to worry about).

Though, the Null proxy could short-circuit all that and `return unless defined wantarray`, which could cover the most common cases and still provide some value.
