### ISSUE TITLE
Log::Any::Proxy::Null not indexed?

### ISSUE THREAD

**Issue by perlancar** [preaction/Log-Any#47]
I'm looking at Log-Any-1.042 release. The package Log::Any::Proxy::Null is not excluded from the index according to the dist metadata, yet it's not in PAUSE's 02packages.details.txt.gz as of this writing. There might be other packages too missing from the index, haven't checked.

**Comment by preaction** [comment]
I've sent an e-mail to the PAUSE admins about this, and hopefully they'll get me the ownership of that package. Right now it has no owner, but it has a co-maint, which is a really weird state for a package to be in. Thanks for letting me know!

**Comment by preaction** [comment]
Looks like the PAUSE pixies fixed it now. The latest release (1.045) is indexed correctly.
