### ISSUE TITLE
Stringification of refs 

### ISSUE THREAD

**Issue by mephinet** [preaction/Log-Any#48]
This has been bugging me for some time:
When migration old code from printing to stdout to using Log::Any, I try to use `$log->infof()` for concatenating strings. This breaks code where part of the printed string is a reference which has an overloaded stringification. In that case, I would expect the stringification to occur, but it does not happen.

One example are URI instances. Printing them using `print "Fetching $uri"` does the right thing, whereas `$log->infof('Fetching %s', $uri),` results in:

> Fetching bless( do{(my $o = "http://slashdot.org/")}, 'URI::http' )

The string overloading is implemented like this:
https://metacpan.org/source/ETHER/URI-1.71/lib/URI.pm#L25
I've created a (failing) unittest for the expected behaviour: https://gist.github.com/mephinet/c3e3d93c805381155712da46b3801edd

Do you think we can improve the behaviour of Log::Any without unwanted side effects?

**Comment by preaction** [comment]
I'm for this: Not treating objects with string overloading correctly breaks the encapsulation of the object. As to whether we can do it without breaking existing uses/users, that's up to debate. I'm willing to try it and ask about it and see if anyone is relying on the old behavior and we can find a way forward for them.
