### ISSUE TITLE
Unicode symbols

### ISSUE THREAD

**Issue by denis-it** [preaction/Log-Any#54]
Hi guys and thanks for the great module! 

I have a question for you and I can't found another way to ask you so probably this ticket is not an issue (sorry if so). I'm a newbie on Perl and I have Unicode problems all the time (I use Russian strings in my project). So here is my problem: I want to see Russian symbols in the log, but they looks like this: `\x{41c}\x{43e}\x{451}`. Is it possible to see valid symbols with your module? What should I do for that? Thanks in advance!

Here is how I'm using your modules:
```perl
package Log;

use strict;
use warnings;
use utf8;

use Log::Any ();
use Log::Any::Adapter ('Stdout');
use Log::Any::For::Std;

sub new {
	my ($class, $category) = @_;
	my $log = Log::Any->get_logger(category => $category // "general");
	my $self = {log => $log};
	bless $self, $class;
}

sub infof {
	my ($self, $message, @params) = @_;
	$self->{log}->infof($message, @params); # <-- $message has Russian symbols
}
```

**Comment by preaction** [comment]
I think the thing you need to do is to make sure that STDOUT is set to accept UTF-8, which you can do via this: http://perldoc.perl.org/perlunicook.html#%211e-15%3a-Declare-STD%7bIN%2cOUT%2cERR%7d-to-be-utf8

I'll leave this open to add a note to both the Stdout and Stderr adapters to recommend this for these situations.

**Comment by denis-it** [comment]
Thanks for the answer!

Unfortunately configuring `STDOUT` didn't helped me, so I continued research and found that `Data::Dumper` dumps data in that strange way. I googled around a bit and found great module named [Data::Dumper::AutoEncode](https://metacpan.org/pod/Data::Dumper::AutoEncode) that solves my problem. I've written custom formatter using AutoEncode and it works like a charm now! :sunglasses:

So the issue is solved, thanks for your help and thanks @bayashi for useful module! :+1:

**Comment by preaction** [comment]
Ohhh! It's Data::Dumper doing it. Alright, I'll instead add a note about using that module in the case where you want to see those high-bit characters. Do you have an example of configuring a formatter that I can add to the docs?

**Comment by denis-it** [comment]
Sure! I've created a [gist](https://gist.github.com/denis-it/2ad28bcdbc734e2b7c67600b5174cfef) for you.

**Comment by preaction** [comment]
I added a `TIPS` section to Log::Any::Proxy with an example formatter that uses Data::Dumper::AutoEncode. Thanks for the sample code!
