### ISSUE TITLE
Log levels detection for Stderr, Stdout, etc..

### ISSUE THREAD

**Issue by 0x62ash** [preaction/Log-Any#55]
Hello,
Looks like Log::Any doesn't detect `WARN` log level because `LOG_LEVEL_ALIASES` in lower case and matching is case-sensitive.

And I think that if detection is failed then adapter should choose default log level, instead of producing ` Use of uninitialized value in numeric le (<=) at /Users/bash/Workshop/perl5/lib/perl5/Log/Any/Adapter/Stderr.pm line 44.`

**Comment by preaction** [comment]
I don't really like the idea of silently absorbing an obvious error condition. So, I think we could do two things:

1) [ ] Run all log level aliases through `lc`. All the regular log levels work with any kind of casing, so we should accept all log level aliases with any case as well.
2) [ ] If we can't determine the numeric log level inside the Adapter, send a specific `warn` message detailing the problem (using Perl's `warn` and `$log->warn`) and default to the original default (for Stderr, Stdout, File, and Syslog it is "trace").

If we do both of these things, it should prevent logging messages getting lost and still alert people that their wishes aren't being honored for a reason.

Would this solve your problem?

**Comment by 0x62ash** [comment]
Absolutely agree

**Comment by preaction** [comment]
This is finally released to CPAN as a stable 1.048 release. Thanks for the help!
