### ISSUE TITLE
Using LOG_ANY_DEFAULT_ADAPTER with no adapters configured in the code

### ISSUE THREAD

**Issue by tm604** [preaction/Log-Any#59]
I'd love to use the `LOG_ANY_DEFAULT_ADAPTER` feature from 1.050, but one of the use-cases I was hoping for does not seem to be supported.

Specifically, this does not generate any output:

    LOG_ANY_DEFAULT_ADAPTER=Stdout perl -e'use Log::Any qw($log); $log->info("here")'

Far as I can tell, it ends up with the Null proxy since it does not check the env variable?

**Comment by mephinet** [comment]
Thanks for giving the devel release a try, @tm604, and reporting this issue - I'll take a look at it!

**Comment by preaction** [comment]
The fix for this is released in 1.051-TRIAL, just uploaded to PAUSE. Thanks for the report and the patch!
