### ISSUE TITLE
binmode attribute not work

### ISSUE THREAD

**Issue by MadLord80** [preaction/Log-Any#72]
In Log::Any::Adapter::File package very strange definition:
`my $binmode ||= ':utf8';`
This dont work if we use (example):
`Log::Any::Adapter->set('File', $file, log_level => 'trace', binmode => ':raw');`
Binmode remainds default (utf8).

My suggestion:
```
- my $binmode ||= ':utf8';
- $binmode = ":$binmode" unless substr($binmode,0,1) eq ':';
+ my $binmode = (substr($self->{binmode},0,1) ne ':') ? ':utf8' : $self->{binmode};
```

**Comment by preaction** [comment]
Thanks for the report! An easier solution would be to `my $binmode = $self->{binmode} || ':utf8';` which I think is what the code was supposed to be. I've added the fix and released v1.705 to CPAN.

**Comment by preaction** [comment]
Why does the condition not work?

```
$ perl -E'$binmode = "raw"; say substr( $binmode, 0, 1 );'
r
$ perl -E'$binmode = ":raw"; say substr( $binmode, 0, 1 );'
:
$ perl -E'$binmode = "raw"; $binmode = ":$binmode" unless substr( $binmode, 0, 1 ) eq ":"; say $binmode'
:raw
$ perl -E'$binmode = ":raw"; $binmode = ":$binmode" unless substr( $binmode, 0, 1 ) eq ":"; say $binmode'
:raw
```

However, notice what happens if I do not use parens:

```
$ perl -E'$binmode = "raw"; $binmode = ":$binmode" unless substr $binmode, 0, 1 eq ":"; say $binmode'
:raw
$ perl -E'$binmode = ":raw"; $binmode = ":$binmode" unless substr $binmode, 0, 1 eq ":"; say $binmode'
::raw
```

That doubles the colon, but it's still adding a colon. In none of these cases is a colon not added to `$binmode`.

You're going to have to give me a failing test case that I can reproduce on my machine.

**Comment by MadLord80** [comment]
ok, sorry...i was wrong )))...
